# Generated by Django 3.2.11 on 2026-06-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_abnormal',
            field=models.BooleanField(default=False),
        ),
    ]
