# Generated by Django 3.2.11 on 2026-06-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_order_is_abnormal'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_off_shelf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
